
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssvgnlbzztxobvilucvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzdmdubGJ6enR4b2J2aWx1Y3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MzgwNTQsImV4cCI6MjA1OTAxNDA1NH0._HuCiYiaGv4RdjDZhAAPeXqnWll0DlZLJiSt3HgcOfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
