
// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import {
  assertSafeAuthHost,
  getNieuweVloerAnonKey,
  getNieuweVloerApiUrl,
  hasNieuweVloerAnonKey,
} from "@/config/api";

const SUPABASE_URL = getNieuweVloerApiUrl();
const SUPABASE_PUBLISHABLE_KEY = getNieuweVloerAnonKey();

assertSafeAuthHost(SUPABASE_URL);

if (import.meta.env.DEV) {
  console.info("[API] Auth/REST host:", SUPABASE_URL, "anon key set:", hasNieuweVloerAnonKey());
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storageKey: "nv-admin-auth",
  },
});

export const AUTH_API_URL = SUPABASE_URL;
